cache:
  pipeline: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: HIGH
  image: maven:3.6.3-jdk-8

jobs:
  main:
    requires: [~pr, ~commit]
    secrets:
      - COVERALLS_TOKEN
    steps:
      - build: mvn -B clean verify
      - coverage: mvn coveralls:report

  release:
    requires: [~tag:/^bullet-spark-\d+\.\d+\.\d+/]
    secrets:
      - SONATYPE_USERNAME
      - SONATYPE_PASSWORD
      - GPG_PASSPHRASE
      - GPG_ENCPHRASE
    steps:
      - publish: screwdriver/release.sh
