/*
 *  Copyright 2018, Yahoo Inc.
 *  Licensed under the terms of the Apache License, Version 2.0.
 *  See the LICENSE file associated with the project for terms.
 */
package com.yahoo.bullet.spark.data

import com.yahoo.bullet.common.BulletError
import com.yahoo.bullet.pubsub.Metadata

/**
 * Class to wrap errors generated by Bullet.
 *
 * @constructor Create a data wrapper for errors.
 * @param metadata The metadata information associated with the query.
 * @param errors   The List of Error associated with the query.
 */
class BulletErrorData(metadata: Metadata, val errors: List[BulletError]) extends BulletData(metadata) {
  /**
   * @constructor Create a data wrapper for errors.
   * @param meta   The metadata information associated with the query.
   * @param errors The variable length of errors associated with the query.
   */
  def this(meta: Metadata, errors: BulletError*) {
    this(meta, errors.toList)
  }
}
